In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv(r"C:\Users\neela\Downloads\fear_greed_index.csv")
df2=pd.read_csv(r"C:\Users\neela\Downloads\historical_data.csv")

In [3]:
df1.head(20)

     timestamp  value classification        date
0   1517463000     30           Fear  2018-02-01
1   1517549400     15   Extreme Fear  2018-02-02
2   1517635800     40           Fear  2018-02-03
3   1517722200     24   Extreme Fear  2018-02-04
4   1517808600     11   Extreme Fear  2018-02-05
5   1517895000      8   Extreme Fear  2018-02-06
6   1517981400     36           Fear  2018-02-07
7   1518067800     30           Fear  2018-02-08
8   1518154200     44           Fear  2018-02-09
9   1518240600     54        Neutral  2018-02-10
10  1518327000     31           Fear  2018-02-11
11  1518413400     42           Fear  2018-02-12
12  1518499800     35           Fear  2018-02-13
13  1518586200     55          Greed  2018-02-14
14  1518672600     71          Greed  2018-02-15
15  1518759000     67          Greed  2018-02-16
16  1518845400     74          Greed  2018-02-17
17  1518931800     63          Greed  2018-02-18
18  1519018200     67          Greed  2018-02-19
19  1519104600     74          Greed  2018-02-20

In [4]:
df2.head(5)

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [5]:
df1.isnull().sum()

timestamp         0
value             0
classification    0
date              0
dtype: int64

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   object
 3   date            2644 non-null   object
dtypes: int64(2), object(2)
memory usage: 82.8+ KB

In [7]:
df1.duplicated().sum()

0

In [8]:
df1['date']=pd.to_datetime(df1['date'])

In [9]:
df2.isnull().sum()

Account             0
Coin                0
Execution Price     0
Size Tokens         0
Size USD            0
Side                0
Timestamp IST       0
Start Position      0
Direction           0
Closed PnL          0
Transaction Hash    0
Order ID            0
Crossed             0
Fee                 0
Trade ID            0
Timestamp           0
dtype: int64

In [10]:
df2.head(2)

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12

In [11]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  object
 1   Coin              211224 non-null  object
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  object
 6   Timestamp IST     211224 non-null  object
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  object
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  object
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), object(6)
memory usage: 24.4+ MB

In [12]:
df2.columns

Index(['Account', 'Coin', 'Execution Price', 'Size Tokens', 'Size USD', 'Side',
       'Timestamp IST', 'Start Position', 'Direction', 'Closed PnL',
       'Transaction Hash', 'Order ID', 'Crossed', 'Fee', 'Trade ID',
       'Timestamp'],
      dtype='object')

In [13]:
df2['Timestamp IST'] = pd.to_datetime(df2['Timestamp IST'], format='%d-%m-%Y %H:%M')

In [14]:
df2['Timestamp'] = pd.to_datetime(df2['Timestamp'], unit='ms')

In [15]:
df2.head(2)

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,2024-12-02 22:50:00,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,2024-10-27 03:33:20
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,2024-12-02 22:50:00,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,2024-10-27 03:33:20

In [16]:
df1['date'] = pd.to_datetime(df1['date']).dt.date

In [17]:
df2['date'] = pd.to_datetime(df2['Timestamp']).dt.date

In [18]:
df2.columns

Index(['Account', 'Coin', 'Execution Price', 'Size Tokens', 'Size USD', 'Side',
       'Timestamp IST', 'Start Position', 'Direction', 'Closed PnL',
       'Transaction Hash', 'Order ID', 'Crossed', 'Fee', 'Trade ID',
       'Timestamp', 'date'],
      dtype='object')

In [19]:
m=pd.merge(df1,df2,on='date',how='outer')

In [20]:
daily_pnl = df2.groupby(['date','Account'])['Closed PnL'].sum().reset_index()

In [21]:
daily_pnl

           date                                     Account     Closed PnL
0    2023-03-28  0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891       0.000000
1    2023-11-14  0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891       0.000000
2    2023-11-14  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23     155.503357
3    2024-03-09  0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891   -5564.016140
4    2024-03-09  0x430f09841d65beb3f27765503d0f850b8bce7713       0.000000
..          ...                                         ...            ...
97   2025-06-15  0xae5eacaf9c6b9111fd53034a602c192a04e082ed   38168.354860
98   2025-06-15  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23  102460.171640
99   2025-06-15  0xbaaaf6571ab7d571043ff1e313a9609a10637864       6.593538
100  2025-06-15  0xbd5fead7180a9c139fa51a103cb6a2ce86ddb5c3 -116594.595363
101  2025-06-15  0xbee1707d6b44d4d52bfe19e41f8a828645437aab   24897.574309

[102 rows x 3 columns]

# win rate

In [22]:
win_rate=(df2['Closed PnL'] > 0).mean()

In [23]:
win_rate

0.4112648183918494

# average trade size

In [24]:
avg_trade_size=df2['Size USD'].mean()

In [25]:
avg_trade_size

5639.4512103738225

# leverage distribution

# number of trades per day

In [26]:
num_trades_day= df2.groupby('date').size().reset_index(name='num_trades')

In [27]:
num_trades_day

         date  num_trades
0  2023-03-28           3
1  2023-11-14        1045
2  2024-03-09        6962
3  2024-07-03        7141
4  2024-10-27       35241
5  2025-02-19      133871
6  2025-06-15       26961

# long/short ratio

In [28]:
long=(df2['Direction']=='Buy').sum()
short=(df2['Direction']=='Sell').sum()

# RATIO

In [29]:
ratio=long/(long + short)

In [30]:
ratio*100

45.64968048500737

# ANALYSIS

Q1=Does performance (PnL, win rate, drawdown proxy) differ between Fear vs Greed days?

In [31]:
# LETS TAKE ON AVG

In [32]:
m1=pd.merge(df2, df1[['date','classification']], on='date', how='left')

In [33]:
(m1.groupby('classification')['Closed PnL'].mean().nlargest(2))

classification
Greed    87.894859
Fear     50.047622
Name: Closed PnL, dtype: float64

In [34]:
(m1.groupby('classification')['Closed PnL'].apply(lambda x: (x > 0).mean()))*100

classification
Extreme Greed    49.008905
Fear             41.514592
Greed            44.647138
Neutral          31.718247
Name: Closed PnL, dtype: float64

In [35]:
(m1.groupby('classification')['Closed PnL'].apply(lambda x: x[x < 0].mean()))

classification
Extreme Greed    -86.703571
Fear            -150.445182
Greed           -178.268548
Neutral         -301.002712
Name: Closed PnL, dtype: float64

In [36]:
# YES  performance (PnL, win rate, drawdown proxy) differ between Fear vs Greed days

Q2 = Do traders change behavior based on sentiment (trade frequency, leverage, long/short bias, position sizes)

In [37]:
(m1.groupby('classification').size()).sort_values(ascending=False)

classification
Fear             133871
Greed             36289
Neutral            7141
Extreme Greed      6962
dtype: int64

In [38]:
(m1.groupby('classification')['Size USD'].mean())

classification
Extreme Greed    5660.265764
Fear             5259.977837
Greed            3182.883845
Neutral          3058.848110
Name: Size USD, dtype: float64

In [39]:
(m1.groupby('classification')['Direction'].apply(lambda x: (x == 'Buy').mean()))

classification
Extreme Greed    0.012640
Fear             0.059587
Greed            0.159993
Neutral          0.110069
Name: Direction, dtype: float64

On Fear days traders are far more active and take bigger positions, but mostly short. On Greed days they trade less, with smaller positions, and show a stronger long bias

In [40]:
df1.columns

Index(['timestamp', 'value', 'classification', 'date'], dtype='object')

In [41]:
df2.columns

Index(['Account', 'Coin', 'Execution Price', 'Size Tokens', 'Size USD', 'Side',
       'Timestamp IST', 'Start Position', 'Direction', 'Closed PnL',
       'Transaction Hash', 'Order ID', 'Crossed', 'Fee', 'Trade ID',
       'Timestamp', 'date'],
      dtype='object')